name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Get tag name
        id: tag_name
        run: echo ::set-output name=TAG::${{ github.event.release.tag_name }}

      - name: Create ZIP file excluding specific files
        run: |
          zip -r ${{ steps.tag_name.outputs.TAG }}.zip . -x "LICENSE" -x ".gitattributes" -x "README.md" -x ".git/*" -x ".github/*"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.tag_name.outputs.TAG }}.zip
          asset_name: ${{ steps.tag_name.outputs.TAG }}.zip
          asset_content_type: application/zip

      - name: Add installation instructions to release
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ github.event.release.id }},
              body: `${{ github.event.release.body }}

              ## インストール方法
              1. **${{ steps.tag_name.outputs.TAG }}.zipをダウンロード**：
              ![image](https://github.com/hayabusa255/SCPSLTranslationJP/assets/140249828/47f1eb3f-0004-4834-801a-248fd2f8a4d0)
              2. **ディレクトリにフォルダごと入れる**：
                  \`\\SteamLibrary\\steamapps\\common\\SCP Secret Laboratory\\Translations\` にフォルダごと入れてください。ディレクトリの開き方はSteamを開いて以下の画像のようにして開きます。
                  ![image](https://github.com/hayabusa255/SCPSLTranslationJP/assets/140249828/b7a3309b-cee3-44ac-92be-e97165cda390)
              3. **ゲーム内設定から言語を変更する**：
                  ![image](https://github.com/hayabusa255/SCPSLTranslationJP/assets/140249828/5f85438c-641a-4fcc-8641-d13ed887ee12)
                  
                  翻訳ファイルを完全に適用するためにゲームを再起動することを推奨します。
              `
            })
