name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Get tag name
        id: tag_name
        run: echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Create ZIP file excluding specific files
        run: |
          zip -r ${{ env.TAG }}.zip . -x "LICENSE" -x ".gitattributes" -x "README.md" -x ".git/*" -x ".github/*"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.TAG }}.zip
          asset_name: ${{ env.TAG }}.zip
          asset_content_type: application/zip

      - name: Update release description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view ${{ github.event.release.tag_name }} --json body -q .body > old_body.txt
          echo "## インストール方法
          1. **${{ env.TAG }}.zipをダウンロード**：
          ![image](https://github.com/hayabusa255/SCPSLTranslationJP/assets/140249828/47f1eb3f-0004-4834-801a-248fd2f8a4d0)
          2. **ディレクトリにフォルダごと入れる**：
              \`\\SteamLibrary\\steamapps\\common\\SCP Secret Laboratory\\Translations\` にフォルダごと入れてください。ディレクトリの開き方はSteamを開いて以下の画像のようにして開きます。
              ![image](https://github.com/hayabusa255/SCPSLTranslationJP/assets/140249828/b7a3309b-cee3-44ac-92be-e97165cda390)
          3. **ゲーム内設定から言語を変更する**：
              ![image](https://github.com/hayabusa255/SCPSLTranslationJP/assets/140249828/5f85438c-641a-4fcc-8641-d13ed887ee12)

              翻訳ファイルを完全に適用するためにゲームを再起動することを推奨します。" > install_instructions.txt
          gh release edit ${{ github.event.release.tag_name }} --notes-file old_body.txt --notes-file install_instructions.txt

      - name: Delete source ZIP asset
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const release = releases.data.find(r => r.id === ${{ github.event.release.id }});
            const assets = await github.rest.repos.listReleaseAssets({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
            });
            const sourceAsset = assets.data.find(a => a.name === 'Source code (zip)');
            if (sourceAsset) {
              await github.rest.repos.deleteReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                asset_id: sourceAsset.id,
              });
            }
