name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Create ZIP file excluding specific files
        run: |
          zip -r ${{ github.event.release.tag_name }}.zip . -x "LICENSE" -x ".gitattributes" -x "README.md" -x ".git/*" -x ".github/*"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ github.event.release.tag_name }}.zip
          asset_name: ${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
