name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create ZIP file excluding specific files
        run: |
          zip -r release_${{ github.ref_name }}.zip . -x ".gitattributes" -x "README.md" -x "LICENSE" -x ".github/workflows/*"

      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            This release contains the following updates:
            - Feature 1
            - Feature 2
            - Tag description: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_${{ github.ref_name }}.zip
          asset_name: release_${{ github.ref_name }}.zip
          asset_content_type: application/zip
